#ifndef __MSGTYPE_DEF_H__
#define __MSGTYPE_DEF_H__

#define DECLARE_MESSAGE_TYPE(name, id) \
    const int name = id;\
    const int type##id = id;

namespace common
{
// 易盛系统ID
enum ESYSTEM_ID
{
    // 行情服务器
    ESI_QUOTE_SERVER            = 1,
    // 行情网关
    ESI_QUOTE_GATEWAY           = 2,
    // 交易网关
    ESI_TRADE_GATEWAY           = 3,
    // 数据同步服务器
    ESI_DB_SERVER               = 4,
    // 风险试算服务器
    ESI_TRIAL_SERVER            = 5,
    // delta服务器
    ESI_DELTA_SERVER            = 6,
};

///////////////////////////////////////////////////////////////////////////////
//heartbeat client
DECLARE_MESSAGE_TYPE(TYPE_SYSTEM_HEARTBEAT_CLIENT, 1)
//heartbeat server
DECLARE_MESSAGE_TYPE(TYPE_SYSTEM_HEARTBEAT_SERVER, 2)

DECLARE_MESSAGE_TYPE(TYPE_SYSTEM_STATUS_PUSH, 1000)


///////////////////////////////////////////////////////////////////////////////
//tradeway position rsp
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_POSITION_RSP, 20000);
//tradeway login req
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_LOGIN_REQ, 20001);
//tradeway login rsp
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_LOGIN_RSP, 20002);
//tradeway trade rsp
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_TRADE_RSP, 20003);
//tradeway order rsp
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_ORDER_RSP, 20004);
//tradeway sync account rsp
DECLARE_MESSAGE_TYPE(TYPE_TRADE_GATEWAY_SYNCACCOUNT_RSP, 20005);
//hsholds
DECLARE_MESSAGE_TYPE(TYPE_HSHOLDS_INFO_RTN, 20006);

///////////////////////////////////////////////////////////////////////////////
//quoteway quote rsp
DECLARE_MESSAGE_TYPE(TYPE_QUOTE_GATEWAY_MARKET_RSP, 30000);
//quoteway login req
DECLARE_MESSAGE_TYPE(TYPE_QUOTE_GATEWAY_LOGIN_REQ, 30001);

//////////////////////////////////////////////////////////////////////////////
//investor deposit rsp
DECLARE_MESSAGE_TYPE(TYPE_CUSTOMER_CASH_DEPOSIT_RSP, 40000);
DECLARE_MESSAGE_TYPE(TYPE_BACKUP_POSITION_SNAPSHOT, 40001);
DECLARE_MESSAGE_TYPE(TYPE_BACKUP_QUOTE_SNAPSHOT, 40002);
DECLARE_MESSAGE_TYPE(TYPE_BACKUP_RATE_SNAPSHOT, 40003);
DECLARE_MESSAGE_TYPE(TYPE_BACKUP_RISK_SNAPSHOT, 40004);
DECLARE_MESSAGE_TYPE(TYPE_BACKUP_WHATIF_SNAPSHOT, 40005);

///////////////////////////////////////////////////////////////////////////////
//trade_gateway to trial_server investor_id rsp
DECLARE_MESSAGE_TYPE(TYPE_CUSTOMER_INVESTOR_ID_RSP, 50000);
//login req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_LOGIN_REQ, 50001);
//login rsp
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_LOGIN_RSP, 50002);
//investor req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INVESTOR_REQ, 50003);
//investor rsp
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INVESTOR_RSP, 50004);
//req instrument
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INSTRUMENT_REQ, 50005);
//rsp instrument
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INSTRUMENT_RSP, 50006);

//subscribe quote req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_QUOTE_REQ, 50007);
//unsubscribe quote req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_QUOTE_REQ, 50008);
//quote rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_QUOTE_RTN, 50009);

//req position
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_POSITION_REQ, 50010);
//rsp position
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_POSITION_RSP, 50011);
//subscribe position req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_POSITION_REQ, 50012);
//unsubscribe position req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_POSITION_REQ, 50013);
//position rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_POSITION_RTN, 50014);

//req trade
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_TRADE_REQ, 50015);
//rsp trade
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_TRADE_RSP, 50016);
//req order
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_ORDER_REQ, 50017);
//rsp order
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_ORDER_RSP, 50018);

//subscribe private_topic req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_PRIVATE_TOPIC_REQ, 50019);
//unsubscribe private_topic req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_PRIVATE_TOPIC_REQ, 50020);
//trade rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_TRADE_RTN, 50021);
//order rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_ORDER_RTN, 50022);

//req sync account
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SYNC_ACCOUNT_REQ, 50023);
//rsp sync account
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SYNC_ACCOUNT_RSP, 50024);
//subscribe sync account req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_SYNCACCOUNT_REQ, 50025);
//unsubscribe sync account req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_SYNCACCOUNT_REQ, 50026);
//sync account rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SYNCACCOUNT_RTN, 50027);

//req margin
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_MARGIN_REQ, 50028);
//rsp margin
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_MARGIN_RSP, 50029);
//subscribe margin req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_MARGIN_REQ, 50030);
//unsubscribe margin req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_MARGIN_REQ, 50031);
//margin rtn
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_MARGIN_RTN, 50032);

//req add riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_ADD_RISKGROUP_REQ, 50033);
//rsp add riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_ADD_RISKGROUP_RSP, 50034);
//req del riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_DEL_RISKGROUP_REQ, 50035);
//rsp del riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_DEL_RISKGROUP_RSP, 50036);
//req edit riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_EDIT_RISKGROUP_REQ, 50037);
//rsp edit riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_EDIT_RISKGROUP_RSP, 50038);
//req insert investor to riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INSERT_INVESTOR_REQ, 50039);
//rsp insert investor to riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INSERT_INVESTOR_RSP, 50040);
//req remove investor from riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_REMOVE_INVESTOR_REQ, 50041);
//rsp remove investor from riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_REMOVE_INVESTOR_RSP, 50042);
//return change risker
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_CHANGE_RISKER_RTN, 50043);
//req query riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_QUERY_RISKGROUP_REQ, 50044);
//rsp query riskgroup
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_QUERY_RISKGROUP_RSP, 50045);
//subscribe total quote req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_TOTAL_QUOTE_REQ, 50055);
//unsubscribe total quote req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_TOTAL_QUOTE_REQ, 50056);
//sub_option_position_risk
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_OPTION_POSITION_RISK, 50057);
//unsub_option_position_risk
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_UNSUB_OPTION_POSITION_RISK, 50058);
//return change risker
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_OPTION_POSITION_RISK_RTN, 50059);
//req_whatif
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_WHATIF_REQ, 50060);
//rsp_whatif
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_WHATIF_RSP, 50061);
//option_argv req
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_QUERY_OPTIONARGV_REQ, 50062);
//option_argv rsp
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_QUERY_OPTIONARGV_RSP, 50063);
//sub_whatif
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_SUB_WHATIF, 50064);
//return whatif
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_WHATIF_RTN, 50065);
//req investor info
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INVESTORINFO_REQ, 50066);
//rsp investor info
DECLARE_MESSAGE_TYPE(TYPE_RISKAPI_INVESTORINFO_RSP, 50067);

///////////////////////////////////////////////////////////////////////////////
//original snap -- inner msg
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_ORIGINALSNAP_RTN, 60001);
//client session
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_CLIENT_SESSION, 60002);

//instrument rtn -- push msg
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_INSTRUMENT_RTN, 60101);
//instrument status rtn
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_INSTRUMENT_STATUS_RTN, 60102);
//quote tick rtn
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_TICK_RTN, 60103);
//quote rtn
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_QUOTE_RTN, 60104);
//kline rtn
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_KLINE_RTN, 60105);

//login req -- req/rsp msg
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_LOGIN_REQ, 61001);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_LOGIN_RSP, 61002);
//subscribe quote req
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_SUB_QUOTE_REQ, 61003);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_SUB_QUOTE_RSP, 61004);
//unsubscribe quote req
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_UNSUB_QUOTE_REQ, 61005);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_UNSUB_QUOTE_RSP, 61006);
//instrument req
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_QUERY_INSTRUMENT_REQ, 61007);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_QUERY_INSTRUMENT_RSP, 61008);
//kline
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_KLINE_REQ, 61009);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_KLINE_RSP, 61010);
//his quote
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_QUERY_HIS_REQ, 61011);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_QUERY_HIS_RSP, 61012);
DECLARE_MESSAGE_TYPE(TYPE_QUOTEAPI_TICK_HIS_RSP, 61014);



///////////////////////////////////////////////////////////////////////////////
//monitor sub req
DECLARE_MESSAGE_TYPE(TYPE_MONITOR_SUB_SERVERINFO_REQ, 70001);
//monitor unsub req
DECLARE_MESSAGE_TYPE(TYPE_MONITOR_UNSUB_SERVERINFO_REQ, 70002);
//monitor serverinfo rtn
DECLARE_MESSAGE_TYPE(TYPE_MONITOR_SERVERINFO_RTN, 70003);


//subscribe system status
DECLARE_MESSAGE_TYPE(TYPE_MONITOR_SYSTEM_STATUS_RTN, 70004);

////////////////////////////////////////////////////////////////////////////////
//manager login req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_LOGIN_REQ, 71001);
//manager login req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_LOGIN_RSP, 71002);
//manager query user info req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_USERINFO_REQ, 71003);
//manager query user info rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_USERINFO_RSP, 71004);
//manager add user req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_USER_REQ, 71005);
//manager add user rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_USER_RSP, 71006);
//manager del user req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_USER_REQ, 71007);
//manager del user rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_USER_RSP, 71008);
//manager edit user req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_EDIT_USER_REQ, 71009);
//manager edit user rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_EDIT_USER_RSP, 71010);
//manager query risker investor info req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_RISKER_INVESTOR_REQ, 71011);
//manager query risker investor info rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_RISKER_INVESTOR_RSP, 71012);
//manager query state investor info req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_STATE_INVESTOR_REQ, 71013);
//manager query state investor info rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_STATE_INVESTOR_RSP, 71014);
//manager add investor req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_INVESTOR_REQ, 71015);
//manager add investor rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_INVESTOR_RSP, 71016);
//manager del investor req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_INVESTOR_REQ, 71017);
//manager del investor rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_INVESTOR_RSP, 71018);
//manager change tree rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CHANGE_TREE_RTN, 71019);
//manager change risker investor rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CHANGE_RISKER_INVESTOR_RTN, 71020);
//manager change investor rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CHANGE_INVESTOR_RTN, 71021);
//manager query insmrgnrate info req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_INSMRGNRATE_REQ, 71022);
//manager query insmrgnrate info rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_INSMRGNRATE_RSP, 71023);
//manager edit insmrgnrate req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_EDIT_INSMRGNRATE_REQ, 71024);
//manager edit insmrgnrate rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_EDIT_INSMRGNRATE_RSP, 71025);
//manager change insmrgnrate rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CHANGE_INSMRGNRATE_RTN, 71026);
//manager option_argv req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_OPTIONARGV_REQ, 71027);
//manager option_argv rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_QUERY_OPTIONARGV_RSP, 71028);
//manager option_argv_adj req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADJ_OPTIONARGV_REQ, 71029);
//manager option_argv_adj rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADJ_OPTIONARGV_RSP, 71030);
//manager option_argv rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_OPTIONARGV_RTN, 71031);
//manager contract req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CONTRACT_REQ, 71032);
//manager contract rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_CONTRACT_RSP, 71033);
//manager investor info req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_INVESTORINFO_REQ, 71034);
//manager investor info rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_INVESTORINFO_RSP, 71035);
//manager add insmrgnrate req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_INSMRGNRATE_REQ, 71036);
//manager add insmrgnrate rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_INSMRGNRATE_RSP, 71037);
//manager add insmrgnrate rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_ADD_INSMRGNRATE_RTN, 71038);
//manager del insmrgnrate req
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_INSMRGNRATE_REQ, 71039);
//manager del insmrgnrate rsp
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_INSMRGNRATE_RSP, 71040);
//manager del insmrgnrate rtn
DECLARE_MESSAGE_TYPE(TYPE_MANAGER_DEL_INSMRGNRATE_RTN, 71041);
}
#endif
